name: Build wheels

on:
  workflow_call:
    inputs:
      libfranka-version:
        required: true
        type: string

env:
  PYBIN_SUPPORTED_VERSIONS: "cp3(7m|8|9|10|11|12)"

jobs:
  build_wheels:
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/manylinux2014_x86_64

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setting up pip
        run: |
          ./docker/common/manylinux-setup-pip

      - name: Install dependencies
        run: |
          set -a 
          . ./dependency_versions
          set +a
          ./docker/common/install-dependencies

      - name: Python package
        run: |
          yum -y install zip
          ./docker/common/manylinux-build-wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: output
